[package]
name = "chap03"
version = "0.1.0"
authors = ["varusan <nakamura@note.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"