[package]
name = "chap04"
version = "0.1.0"
authors = ["varu3dbox <subplus.1027magi+tech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.4.1"
